# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: aprilmintacpineda.github.io/blog
email: aprilmintacpineda@gmail.com
description: Inspiring and useful contents available for everyone, anytime, anywhere.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: https://aprilmintacpineda.github.io/blog
portfolio: https://aprilmintacpineda.github.io/
twitter_username: ""
github_username:  aprilmintacpineda
category_list:
  - How-Tos
  - Thoughts
  - Theology
permalink: pretty

author: April Mintac Pineda
keywords: blog, learn, read.

collections:
  policies:
    output: true

# Build settings
sass:
  sass_dir: ./public/styles
  style: compressed
# Conversion
markdown: kramdown
highlighter: rouge
# Markdown Processors
kramdown:
  input: GFM
  syntax_highlighter: rouge
# theme: minima
plugins:
  # - jekyll-feed
  # - jekyll-minifier
  # - octopress-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# port
port: 8000